version: "3.8"

services:
    api:
        build: ./api
        ports:
            - "8080:8080"
        environment:
            - PORT=8080

        depends_on:
            - db
            - rabbitmq

    data-procesor:
        build: ./data-processor
        ports:
            - "8081:8081"
        environment:
            - PORT=8081

        depends_on:
            - db
            - rabbitmq

    lead-search:
        build: ./lead-search
        ports:
            - "8082:8082"
        environment:
            - PORT=8082

        depends_on:
            - db

    db:
        image: postgres:13
        environment:
            POSTGRES_DB: leadsdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    ai:
        build: ./ai_service
        volumes:
            - ./ai:/app/src
            - ./proto:/app/proto
        depends_on:
            - db
        command: ["python", "main.py"]

    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    postgres_data:
