version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: leadsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ai:
    build: ./ai_service
    depends_on:
      - db
    command: ["python", "main.py"]

volumes:
  postgres_data:
