INSERT INTO city (name, state_id) VALUES ('DESCALVADO', 25);
INSERT INTO city (name, state_id) VALUES ('DIADEMA', 25);
INSERT INTO city (name, state_id) VALUES ('DIRCE REIS', 25);
INSERT INTO city (name, state_id) VALUES ('DIVINOLÂNDIA', 25);
INSERT INTO city (name, state_id) VALUES ('DOBRADA', 25);
INSERT INTO city (name, state_id) VALUES ('DOIS CÓRREGOS', 25);
INSERT INTO city (name, state_id) VALUES ('DOLCINÓPOLIS', 25);
INSERT INTO city (name, state_id) VALUES ('DOURADO', 25);
INSERT INTO city (name, state_id) VALUES ('DRACENA', 25);
INSERT INTO city (name, state_id) VALUES ('DUARTINA', 25);
INSERT INTO city (name, state_id) VALUES ('DUMONT', 25);
INSERT INTO city (name, state_id) VALUES ('ECHAPORÃ', 25);
INSERT INTO city (name, state_id) VALUES ('ELDORADO', 25);
INSERT INTO city (name, state_id) VALUES ('ELIAS FAUSTO', 25);
INSERT INTO city (name, state_id) VALUES ('ELISIÁRIO', 25);
INSERT INTO city (name, state_id) VALUES ('EMBAÚBA', 25);
INSERT INTO city (name, state_id) VALUES ('EMBU', 25);
INSERT INTO city (name, state_id) VALUES ('EMBU-GUAÇU', 25);
INSERT INTO city (name, state_id) VALUES ('EMILIANÓPOLIS', 25);
INSERT INTO city (name, state_id) VALUES ('ENGENHEIRO COELHO', 25);
INSERT INTO city (name, state_id) VALUES ('ESPÍRITO SANTO DO PINHAL', 25);
INSERT INTO city (name, state_id) VALUES ('ESPÍRITO SANTO DO TURVO', 25);
INSERT INTO city (name, state_id) VALUES ('ESTIVA GERBI', 25);
INSERT INTO city (name, state_id) VALUES ('ESTRELA DO NORTE', 25);
INSERT INTO city (name, state_id) VALUES ('ESTRELA D''OESTE', 25);
INSERT INTO city (name, state_id) VALUES ('EUCLÍDES DA CUNHA PAULISTA', 25);
INSERT INTO city (name, state_id) VALUES ('FARTURA', 25);
INSERT INTO city (name, state_id) VALUES ('FERNANDO PRESTES', 25);
INSERT INTO city (name, state_id) VALUES ('FERNANDÓPOLIS', 25);
INSERT INTO city (name, state_id) VALUES ('FERNÃO', 25);
INSERT INTO city (name, state_id) VALUES ('FERRAZ DE VASCONCELOS', 25);
INSERT INTO city (name, state_id) VALUES ('FLORA RICA', 25);
INSERT INTO city (name, state_id) VALUES ('FLOREAL', 25);
INSERT INTO city (name, state_id) VALUES ('FLÓRIDA PAULISTA', 25);
INSERT INTO city (name, state_id) VALUES ('FLORÍNIA', 25);
INSERT INTO city (name, state_id) VALUES ('FRANCA', 25);
INSERT INTO city (name, state_id) VALUES ('FRANCISCO MORATO', 25);
INSERT INTO city (name, state_id) VALUES ('FRANCO DA ROCHA', 25);
INSERT INTO city (name, state_id) VALUES ('GABRIEL MONTEIRO', 25);
INSERT INTO city (name, state_id) VALUES ('GÁLIA', 25);
INSERT INTO city (name, state_id) VALUES ('GARÇA', 25);
INSERT INTO city (name, state_id) VALUES ('GASTÃO VIDIGAL', 25);
INSERT INTO city (name, state_id) VALUES ('GAVIÃO PEIXOTO', 25);
INSERT INTO city (name, state_id) VALUES ('GENERAL SALGADO', 25);
INSERT INTO city (name, state_id) VALUES ('GETULINA', 25);
INSERT INTO city (name, state_id) VALUES ('GLICÉRIO', 25);
INSERT INTO city (name, state_id) VALUES ('GUAIÇARA', 25);
INSERT INTO city (name, state_id) VALUES ('GUAIMBÊ', 25);
INSERT INTO city (name, state_id) VALUES ('GUAÍRA', 25);
INSERT INTO city (name, state_id) VALUES ('GUAPIAÇU', 25);
INSERT INTO city (name, state_id) VALUES ('GUAPIARA', 25);
INSERT INTO city (name, state_id) VALUES ('GUARÁ', 25);
INSERT INTO city (name, state_id) VALUES ('GUARAÇAÍ', 25);
INSERT INTO city (name, state_id) VALUES ('GUARACI', 25);
INSERT INTO city (name, state_id) VALUES ('GUARANI D''OESTE', 25);
INSERT INTO city (name, state_id) VALUES ('GUARANTÃ', 25);
INSERT INTO city (name, state_id) VALUES ('GUARARAPES', 25);
INSERT INTO city (name, state_id) VALUES ('GUARAREMA', 25);
INSERT INTO city (name, state_id) VALUES ('GUARATINGUETÁ', 25);
INSERT INTO city (name, state_id) VALUES ('GUAREÍ', 25);
INSERT INTO city (name, state_id) VALUES ('GUARIBA', 25);
INSERT INTO city (name, state_id) VALUES ('GUARUJÁ', 25);
INSERT INTO city (name, state_id) VALUES ('GUARULHOS', 25);
INSERT INTO city (name, state_id) VALUES ('GUATAPARÁ', 25);
INSERT INTO city (name, state_id) VALUES ('GUZOLÂNDIA', 25);
INSERT INTO city (name, state_id) VALUES ('HERCULÂNDIA', 25);
INSERT INTO city (name, state_id) VALUES ('HOLAMBRA', 25);
INSERT INTO city (name, state_id) VALUES ('HORTOLÂNDIA', 25);
INSERT INTO city (name, state_id) VALUES ('IACANGA', 25);
INSERT INTO city (name, state_id) VALUES ('IACRI', 25);
INSERT INTO city (name, state_id) VALUES ('IARAS', 25);
INSERT INTO city (name, state_id) VALUES ('IBATÉ', 25);
INSERT INTO city (name, state_id) VALUES ('IBIRÁ', 25);
INSERT INTO city (name, state_id) VALUES ('IBIRAREMA', 25);
INSERT INTO city (name, state_id) VALUES ('IBITINGA', 25);
INSERT INTO city (name, state_id) VALUES ('IBIÚNA', 25);
INSERT INTO city (name, state_id) VALUES ('ICÉM', 25);
INSERT INTO city (name, state_id) VALUES ('IEPÊ', 25);
INSERT INTO city (name, state_id) VALUES ('IGARAÇU DO TIETÊ', 25);
INSERT INTO city (name, state_id) VALUES ('IGARAPAVA', 25);
INSERT INTO city (name, state_id) VALUES ('IGARATÁ', 25);
INSERT INTO city (name, state_id) VALUES ('IGUAPE', 25);
INSERT INTO city (name, state_id) VALUES ('ILHA COMPRIDA', 25);
INSERT INTO city (name, state_id) VALUES ('ILHA SOLTEIRA', 25);
INSERT INTO city (name, state_id) VALUES ('ILHABELA', 25);
INSERT INTO city (name, state_id) VALUES ('INDAIATUBA', 25);
INSERT INTO city (name, state_id) VALUES ('INDIANA', 25);
INSERT INTO city (name, state_id) VALUES ('INDIAPORÃ', 25);
INSERT INTO city (name, state_id) VALUES ('INÚBIA PAULISTA', 25);
INSERT INTO city (name, state_id) VALUES ('IPAUÇU', 25);
INSERT INTO city (name, state_id) VALUES ('IPERÓ', 25);
INSERT INTO city (name, state_id) VALUES ('IPEÚNA', 25);
INSERT INTO city (name, state_id) VALUES ('IPIGUÁ', 25);
INSERT INTO city (name, state_id) VALUES ('IPORANGA', 25);
INSERT INTO city (name, state_id) VALUES ('IPUÃ', 25);
INSERT INTO city (name, state_id) VALUES ('IRACEMÁPOLIS', 25);
INSERT INTO city (name, state_id) VALUES ('IRAPUÃ', 25);
INSERT INTO city (name, state_id) VALUES ('IRAPURU', 25);
INSERT INTO city (name, state_id) VALUES ('ITABERÁ', 25);
INSERT INTO city (name, state_id) VALUES ('ITAÍ', 25);
INSERT INTO city (name, state_id) VALUES ('ITAJOBI', 25);
INSERT INTO city (name, state_id) VALUES ('ITAJU', 25);
INSERT INTO city (name, state_id) VALUES ('ITANHAÉM', 25);
INSERT INTO city (name, state_id) VALUES ('ITAÓCA', 25);
INSERT INTO city (name, state_id) VALUES ('ITAPECERICA DA SERRA', 25);
INSERT INTO city (name, state_id) VALUES ('ITAPETININGA', 25);
INSERT INTO city (name, state_id) VALUES ('ITAPEVA', 25);
INSERT INTO city (name, state_id) VALUES ('ITAPEVI', 25);
INSERT INTO city (name, state_id) VALUES ('ITAPIRA', 25);
INSERT INTO city (name, state_id) VALUES ('ITAPIRAPUÃ PAULISTA', 25);
INSERT INTO city (name, state_id) VALUES ('ITÁPOLIS', 25);
INSERT INTO city (name, state_id) VALUES ('ITAPORANGA', 25);
INSERT INTO city (name, state_id) VALUES ('ITAPUÍ', 25);
INSERT INTO city (name, state_id) VALUES ('ITAPURA', 25);
INSERT INTO city (name, state_id) VALUES ('ITAQUAQUECETUBA', 25);
INSERT INTO city (name, state_id) VALUES ('ITARARÉ', 25);
INSERT INTO city (name, state_id) VALUES ('ITARIRI', 25);
INSERT INTO city (name, state_id) VALUES ('ITATIBA', 25);
INSERT INTO city (name, state_id) VALUES ('ITATINGA', 25);
INSERT INTO city (name, state_id) VALUES ('ITIRAPINA', 25);
INSERT INTO city (name, state_id) VALUES ('ITIRAPUÃ', 25);
INSERT INTO city (name, state_id) VALUES ('ITOBI', 25);
INSERT INTO city (name, state_id) VALUES ('ITU', 25);
INSERT INTO city (name, state_id) VALUES ('ITUPEVA', 25);
INSERT INTO city (name, state_id) VALUES ('ITUVERAVA', 25);
