INSERT INTO city (name, state_id) VALUES ('ADAMANTINA', 25);
INSERT INTO city (name, state_id) VALUES ('ADOLFO', 25);
INSERT INTO city (name, state_id) VALUES ('AGUAÍ', 25);
INSERT INTO city (name, state_id) VALUES ('ÁGUAS DA PRATA', 25);
INSERT INTO city (name, state_id) VALUES ('ÁGUAS DE LINDÓIA', 25);
INSERT INTO city (name, state_id) VALUES ('ÁGUAS DE SANTA BÁRBARA', 25);
INSERT INTO city (name, state_id) VALUES ('ÁGUAS DE SÃO PEDRO', 25);
INSERT INTO city (name, state_id) VALUES ('AGUDOS', 25);
INSERT INTO city (name, state_id) VALUES ('ALAMBARI', 25);
INSERT INTO city (name, state_id) VALUES ('ALFREDO MARCONDES', 25);
INSERT INTO city (name, state_id) VALUES ('ALTAIR', 25);
INSERT INTO city (name, state_id) VALUES ('ALTINÓPOLIS', 25);
INSERT INTO city (name, state_id) VALUES ('ALTO ALEGRE', 25);
INSERT INTO city (name, state_id) VALUES ('ALUMÍNIO', 25);
INSERT INTO city (name, state_id) VALUES ('ÁLVARES FLORENCE', 25);
INSERT INTO city (name, state_id) VALUES ('ÁLVARES MACHADO', 25);
INSERT INTO city (name, state_id) VALUES ('ÁLVARO DE CARVALHO', 25);
INSERT INTO city (name, state_id) VALUES ('ALVINLÂNDIA', 25);
INSERT INTO city (name, state_id) VALUES ('AMERICANA', 25);
INSERT INTO city (name, state_id) VALUES ('AMÉRICO BRASILIENSE', 25);
INSERT INTO city (name, state_id) VALUES ('AMÉRICO DE CAMPOS', 25);
INSERT INTO city (name, state_id) VALUES ('AMPARO', 25);
INSERT INTO city (name, state_id) VALUES ('ANALÂNDIA', 25);
INSERT INTO city (name, state_id) VALUES ('ANDRADINA', 25);
INSERT INTO city (name, state_id) VALUES ('ANGATUBA', 25);
INSERT INTO city (name, state_id) VALUES ('ANHEMBI', 25);
INSERT INTO city (name, state_id) VALUES ('ARAÇARIGUAMA', 25);
INSERT INTO city (name, state_id) VALUES ('ARAÇATUBA', 25);
INSERT INTO city (name, state_id) VALUES ('ARAÇOIABA DA SERRA', 25);
INSERT INTO city (name, state_id) VALUES ('ARAMINA', 25);
INSERT INTO city (name, state_id) VALUES ('ARANDU', 25);
INSERT INTO city (name, state_id) VALUES ('ARAPEÍ', 25);
INSERT INTO city (name, state_id) VALUES ('ARARAQUARA', 25);
INSERT INTO city (name, state_id) VALUES ('ARARAS', 25);
INSERT INTO city (name, state_id) VALUES ('ARCO-ÍRIS', 25);
INSERT INTO city (name, state_id) VALUES ('AREALVA', 25);
INSERT INTO city (name, state_id) VALUES ('AREIAS', 25);
INSERT INTO city (name, state_id) VALUES ('AREIÓPOLIS', 25);
INSERT INTO city (name, state_id) VALUES ('ARIRANHA', 25);
INSERT INTO city (name, state_id) VALUES ('ARTUR NOGUEIRA', 25);
INSERT INTO city (name, state_id) VALUES ('ARUJÁ', 25);
INSERT INTO city (name, state_id) VALUES ('ASPÁSIA', 25);
INSERT INTO city (name, state_id) VALUES ('ASSIS', 25);
INSERT INTO city (name, state_id) VALUES ('ATIBAIA', 25);
INSERT INTO city (name, state_id) VALUES ('AURIFLAMA', 25);
INSERT INTO city (name, state_id) VALUES ('AVAÍ', 25);
INSERT INTO city (name, state_id) VALUES ('AVANHANDAVA', 25);
INSERT INTO city (name, state_id) VALUES ('AVARÉ', 25);
INSERT INTO city (name, state_id) VALUES ('BADY BASSITT', 25);
INSERT INTO city (name, state_id) VALUES ('BALBINOS', 25);
INSERT INTO city (name, state_id) VALUES ('BÁLSAMO', 25);
INSERT INTO city (name, state_id) VALUES ('BANANAL', 25);
INSERT INTO city (name, state_id) VALUES ('BARÃO DE ANTONINA', 25);
INSERT INTO city (name, state_id) VALUES ('BARRA DO CHAPÉU', 25);
INSERT INTO city (name, state_id) VALUES ('BATATAIS', 25);
INSERT INTO city (name, state_id) VALUES ('BAURU', 25);
INSERT INTO city (name, state_id) VALUES ('BEBEDOURO', 25);
INSERT INTO city (name, state_id) VALUES ('BENTO DE ABREU', 25);
INSERT INTO city (name, state_id) VALUES ('BERNARDINO DE CAMPOS', 25);
INSERT INTO city (name, state_id) VALUES ('BERTIOGA', 25);
INSERT INTO city (name, state_id) VALUES ('BILAC', 25);
INSERT INTO city (name, state_id) VALUES ('BIRIGÜI', 25);
INSERT INTO city (name, state_id) VALUES ('BIRITIBA-MIRIM', 25);
INSERT INTO city (name, state_id) VALUES ('BOA ESPERANÇA DO SUL', 25);
INSERT INTO city (name, state_id) VALUES ('BOCAINA', 25);
INSERT INTO city (name, state_id) VALUES ('BOFETE', 25);
INSERT INTO city (name, state_id) VALUES ('BOITUVA', 25);
INSERT INTO city (name, state_id) VALUES ('BOM JESUS DOS PERDÕES', 25);
INSERT INTO city (name, state_id) VALUES ('BOM SUCESSO DE ITARARÉ', 25);
INSERT INTO city (name, state_id) VALUES ('BRAGANÇA PAULISTA', 25);
INSERT INTO city (name, state_id) VALUES ('BRAÚNA', 25);
INSERT INTO city (name, state_id) VALUES ('BREJO ALEGRE', 25);
INSERT INTO city (name, state_id) VALUES ('BRODÓSQUI', 25);
INSERT INTO city (name, state_id) VALUES ('BROTAS', 25);
INSERT INTO city (name, state_id) VALUES ('BURI', 25);
INSERT INTO city (name, state_id) VALUES ('BURITAMA', 25);
INSERT INTO city (name, state_id) VALUES ('BURITIZAL', 25);
INSERT INTO city (name, state_id) VALUES ('CABRÁLIA PAULISTA', 25);
INSERT INTO city (name, state_id) VALUES ('CABREÚVA', 25);
INSERT INTO city (name, state_id) VALUES ('CAÇAPAVA', 25);
INSERT INTO city (name, state_id) VALUES ('CACHOEIRA PAULISTA', 25);
INSERT INTO city (name, state_id) VALUES ('CACONDE', 25);
INSERT INTO city (name, state_id) VALUES ('CAFELÂNDIA', 25);
INSERT INTO city (name, state_id) VALUES ('CAIABU', 25);
INSERT INTO city (name, state_id) VALUES ('CAIEIRAS', 25);
INSERT INTO city (name, state_id) VALUES ('CAIUÁ', 25);
INSERT INTO city (name, state_id) VALUES ('CAJAMAR', 25);
INSERT INTO city (name, state_id) VALUES ('CAJATI', 25);
INSERT INTO city (name, state_id) VALUES ('CAJOBI', 25);
INSERT INTO city (name, state_id) VALUES ('CAJURU', 25);
INSERT INTO city (name, state_id) VALUES ('CAMPINA DO MONTE ALEGRE', 25);
INSERT INTO city (name, state_id) VALUES ('CAMPINAS', 25);
INSERT INTO city (name, state_id) VALUES ('CAMPO LIMPO PAULISTA', 25);
INSERT INTO city (name, state_id) VALUES ('CAMPOS DO JORDÃO', 25);
INSERT INTO city (name, state_id) VALUES ('CAMPOS NOVOS PAULISTA', 25);
INSERT INTO city (name, state_id) VALUES ('CANANÉIA', 25);
INSERT INTO city (name, state_id) VALUES ('CANAS', 25);
INSERT INTO city (name, state_id) VALUES ('CÂNDIDO MOTA', 25);
INSERT INTO city (name, state_id) VALUES ('CÂNDIDO RODRIGUES', 25);
INSERT INTO city (name, state_id) VALUES ('CANITAR', 25);
INSERT INTO city (name, state_id) VALUES ('CAPÃO BONITO', 25);
INSERT INTO city (name, state_id) VALUES ('CAPELA DO ALTO', 25);
INSERT INTO city (name, state_id) VALUES ('CAPIVARI', 25);
INSERT INTO city (name, state_id) VALUES ('CARAGUATATUBA', 25);
INSERT INTO city (name, state_id) VALUES ('CARAPICUÍBA', 25);
INSERT INTO city (name, state_id) VALUES ('CARDOSO', 25);
INSERT INTO city (name, state_id) VALUES ('CASA BRANCA', 25);
INSERT INTO city (name, state_id) VALUES ('CÁSSIA DOS COQUEIROS', 25);
INSERT INTO city (name, state_id) VALUES ('CASTILHO', 25);
INSERT INTO city (name, state_id) VALUES ('CATANDUVA', 25);
INSERT INTO city (name, state_id) VALUES ('CATIGUÁ', 25);
INSERT INTO city (name, state_id) VALUES ('CEDRAL', 25);
INSERT INTO city (name, state_id) VALUES ('CERQUEIRA CÉSAR', 25);
INSERT INTO city (name, state_id) VALUES ('CERQUILHO', 25);
INSERT INTO city (name, state_id) VALUES ('CESÁRIO LANGE', 25);
INSERT INTO city (name, state_id) VALUES ('CHARQUEADA', 25);
INSERT INTO city (name, state_id) VALUES ('CHAVANTES', 25);
INSERT INTO city (name, state_id) VALUES ('CONCHAL', 25);
INSERT INTO city (name, state_id) VALUES ('CONCHAS', 25);
INSERT INTO city (name, state_id) VALUES ('CORDEIRÓPOLIS', 25);
INSERT INTO city (name, state_id) VALUES ('COROADOS', 25);
INSERT INTO city (name, state_id) VALUES ('CORONEL MACEDO', 25);
INSERT INTO city (name, state_id) VALUES ('CORUMBATAÍ', 25);
INSERT INTO city (name, state_id) VALUES ('COSMÓPOLIS', 25);
INSERT INTO city (name, state_id) VALUES ('COSMORAMA', 25);
INSERT INTO city (name, state_id) VALUES ('COTIA', 25);
INSERT INTO city (name, state_id) VALUES ('CRAVINHOS', 25);
INSERT INTO city (name, state_id) VALUES ('CRISTAIS PAULISTA', 25);
INSERT INTO city (name, state_id) VALUES ('CRUZÁLIA', 25);
INSERT INTO city (name, state_id) VALUES ('CRUZEIRO', 25);
INSERT INTO city (name, state_id) VALUES ('CUBATÃO', 25);
INSERT INTO city (name, state_id) VALUES ('CUNHA', 25);
