global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'redis-exporter'
  static_configs:
    - targets: ['redis-exporter:9121']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']

  - job_name: 'data-processor'
    static_configs:
      - targets: ['data-processor:8081']

  - job_name: 'datalake'
    static_configs:
      - targets: ['datalake:8087']

  - job_name: 'scrapper'
    static_configs:
      - targets: ['scrapper:8080']

  - job_name: 'api'
    static_configs:
      - targets: ['api:8085']

  - job_name: 'lead-search'
    static_configs:
      - targets: ['lead-search:8082']

  - job_name: 'validator-service'
    static_configs:
      - targets: ['validator-service:8090']
